import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'm.winkelmann' at '14.11.16 17:53' with Gradle 3.1
 *
 * @author m.winkelmann, @date 14.11.16 17:53
 */
public class LibraryTest {

    @Test public void testSomeLibraryMethod() {
    }
}
